all: sphere main wave
sphere:sphere.c
	cc sphere.c common/music.c common/parse.c -o sphere -lm
main:main.c
	cc main.c common/music.c common/parse.c -o main
wave:wave.c
	cc wave.c common/music.c common/parse.c -o wave -lm

